/**
 * Enrollment API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.48.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Lang {
    /**
     * Lang identifier
     */
    id?: string;

    /**
     * Lang name in native
     */
    name?: string;

    /**
     * consider to set up this lang as default (optional param)
     */
    default?: boolean;

}
