/**
 * Enrollment API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.48.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Suite {
    /**
     * Identifier of the suite
     */
    id?: string;

    /**
     * Suite name
     */
    name?: string;

    /**
     * Exams for this suite
     */
    exams?: Array<string>;

}
