/**
 * Enrollment API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.48.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Threshold } from './threshold';


export interface ThresholdsResponse {
    /**
     * Current page of the search response
     */
    page?: number;

    /**
     * Total pages in the search response
     */
    pageCount?: number;

    /**
     * If the current response is centered to the given user grade
     */
    isCentered?: boolean;

    items?: Array<Threshold>;

}
