/**
 * Enrollment API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.48.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Threshold {
    /**
     * Identifier of the speciality
     */
    id?: string;

    /**
     * Speciality name
     */
    name?: string;

    universityName?: string;

    universityShortName?: string;

    departmentName?: string;

    departmentShortName?: string;

    /**
     * URL to link for further details
     */
    detailsUrl?: string;

    /**
     * Actual threshold level that needed to be enrolled to the given speciality
     */
    threshold?: number;

    /**
     * 'Chances to be enrolled, that may be depicted as a certain color, this depends on user total grades passed as the request'
     */
    chance?: number;

}


